name: Dev Branch Push Workflow

# Trigger the workflow on push events to the 'dev' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    # Run tests
    - name: Run tests
      run: |
        pytest test_app.py

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |
        sshpass -p ${{ secrets.PA_PASSWORD }} scp -o StrictHostKeyChecking=no -r ./ * $PA_USERNAME@pythonanywhere.com:/home/$PA_USERNAME/python-flask/
        sshpass -p ${{ secrets.PA_PASSWORD }} ssh $PA_USERNAME@pythonanywhere.com "cd /home/$PA_USERNAME/python-flask && pip install -r requirements.txt && touch /home/$PA_USERNAME/python-flask/wsgi.py"
